---
- include_role:
    name: "dt-oneagent-classic"

- name: "Ansible | List all known variables and facts"
  debug:
    var: hostvars[inventory_hostname]   

- name: Run a script
  ansible.builtin.script: "{{ role_path }}/files/myscript.sh"
  environment:
    DT_ENV_URL: "{{ dynatrace_tenant_url }}"
  register: script_output

- debug: var=script_output

- name: Run a command
  ansible.builtin.shell:
    cmd: echo "Dynatrace Environment URL $DT_ENV_URL"
  environment:
    DT_ENV_URL: "{{ dynatrace_tenant_url }}"
  register: shell_output

- debug: var=shell_output